### ISSUE TITLE
Add support for casava 1.8 fastq files

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgp_seq_input_val#12]
Currently doesn't support validation of a casava 1.8 format fastq file.

https://en.wikipedia.org/wiki/FASTQ_format#Illumina_sequence_identifiers

1. Need to add method to detect record header format for file
1. If paired verify both share same record header format for first record
1. Rest of file required to use same format
1. Add info to output json indicating header format type

**Comment by keiranmraine** [comment]
Json:

```
{
    ...
    "format": "Illumina",
    or
    "format": "Casava 1.8"
}
```

**Comment by byb121** [comment]
Added in v1.5.0
