### ISSUE TITLE
Manifest will not validate with bz2

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgp_seq_input_val#14]
Looks like the manifest validation code needs updating to allow other compressed types.

Something like `if ext in ('.gz', '.bz2')`:

https://github.com/cancerit/cgp_seq_input_val/blob/8d3130e47573b64ac8806661687c3b4123cfec02/cgp_seq_input_val/manifest.py#L526

This will also need an update:

https://github.com/cancerit/cgp_seq_input_val/blob/8d3130e47573b64ac8806661687c3b4123cfec02/cgp_seq_input_val/config/IMPORT-1.0.json#L39-L40

@yx2, are you happy to do this as part of the cassava changes?  Needed so module can be imported into CGPaaS-manifest

**Comment by byb121** [comment]
found that config JSON earlier and already corrected. I'll make the change in `manifest.py`.
